---
apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: ClusterRole
    metadata:
      name: cert-operator-role
    rules:
      - apiGroups:
        - ""
        attributeRestrictions: null
        resources:
        - services
        - routes
        verbs:
        - create
  - apiVersion: v1
    kind: RoleBinding
    metadata:
      name: cert-operator
      namespace: ${NAMESPACE}
    roleRef:
      name: cert-operator-role
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: ${NAMESPACE}
  - apiVersion: v1
    kind: ClusterRoleBinding
    metadata:
      name: cert-operator-cluster-admin
    roleRef:
      name: cluster-admin
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: ${NAMESPACE}
parameters:
  - name: NAMESPACE
